Portfolio-setup: Mobile Version
3nityGitHub/Mobile-portfolio-setup pull request #2
Opened 2022-12-02 05:39 UTC by 3nityGitHub

## In this PR:

- I added the work section and all the relevant images,
- I added the about me section

2022-12-02 06:54 UTC, emmiiorji requested changes
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

![Ouch-gifs-38715704-365-199](https://user-images.githubusercontent.com/20554583/203522872-2c5eafd3-e90b-4c90-859a-320f26e8a84d.gif)

You have submitted a project that's not sufficiently following the [updated readme template](https://github.com/microverseinc/readme-template). Kindly follow the template to include the table of content and make sure they're links to parts of the readme.

You seem to have some table of content, but the items are not links and some sections are missing from your readme.
![image](https://user-images.githubusercontent.com/20554583/205234330-71cc9bab-f2a7-40a2-91fb-afc7f7f754bc.png)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-02 16:22 UTC, RiyaBulia12 requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi  @3nityGitHub 👋, 

Good job! 🎉 🎉 🎉  There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlight 🎉
- No linter errors :heavy_check_mark:
- Correct GitHub flow :heavy_check_mark:
- Meaningful commit messages ✔️
- License setup correctly  ✔️ 

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._ 🙂 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-02 16:22 UTC, RiyaBulia12 commented on index.html
> +    <button class="see_prjt_buttn flex">See Project</button>
- [ ] It looks like you have not removed the border from all the `See Projects` buttons. Please kindly fix the button design to make it similar to the Figma template. Please try to stick with your selected design template for better UI and consistency. 👍🏽 😃 

| Figma Design | Your Design |
|------------------- | ------------------- |
| ![Figma_1](https://user-images.githubusercontent.com/24832846/205331757-1bc560eb-0502-4675-8701-e1f55c728890.png) | ![Your](https://user-images.githubusercontent.com/24832846/205331795-c8ae83dd-d135-4857-8bcb-9a690105a280.png) |

2022-12-02 16:22 UTC, RiyaBulia12 commented on index.html
> +    <button class="get_resume flex">Get My Resume</button>
- [ ] It looks like you have not removed the border from all the `See Projects` buttons. Please kindly fix the button design to make it similar to the Figma template. Please try to stick with your selected design template for better UI and consistency. 🙂

2022-12-02 19:24 UTC, 3nityGitHub commented on index.html
> +                <li class="Language_skill2"><img class="border_line" src="image folder/Rectangle57.png" alt="rectangle_icon">  Skills
@RiyaBulia12 Thanks for your review, but I still cannot understand what exactly you want me to do here, the my design looks close to the figma design as possible. Kindly revert asap.

Regards.

2022-12-02 22:55 UTC, bobb-Rob approved these changes
## STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳 

Hi @3nityGitHub , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages

## Optional suggestions
### Your logo should be wrapper by a an `a` tag because if should have a link to the home page. This is best practice for website particularly to improve user experience. 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 10:59 UTC, RiyaBulia12 commented on index.html
> +                <li class="Language_skill2"><img class="border_line" src="image folder/Rectangle57.png" alt="rectangle_icon">  Skills
Hi @3nityGitHub, Sorry for the delayed response. It looks like I used the wrong screenshot for comparison. Sorry again for the confusion. I was suggesting you align all the headings in the middle, especially Skills. Something like this in the image below:

<img width="170" alt="Screenshot 2022-12-03 at 4 26 02 PM" src="https://user-images.githubusercontent.com/24832846/205437456-b0656994-3b80-454c-87ef-00c022206b30.png">

2022-12-03 18:24 UTC, merged