Mobile_ Porfolio_Setup: Desktop Version
3nityGitHub/Mobile-portfolio-setup pull request #4
Opened 2022-12-09 08:11 UTC by 3nityGitHub

## In this PR:
- I included media queries to the pages can be compatible with large screens like desktops
- I modified index.HTML files to suit the media query
- I modified styles.CSS to suit the media query

2022-12-09 08:50 UTC, roshan-bajgain requested changes
Hi @3nityGitHub, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
## Required Changes ♻️
- [ ] Your mobile design does not look as expected. please fix the horizontal scrolling. It has a problem with horizontal scrolling. please fix it
### Design
![Screenshot 2022-12-09 143217](https://user-images.githubusercontent.com/81727988/206662484-5e8a7745-4441-4cdf-8f1e-6467c9e9db7b.png)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-09 08:50 UTC, roshan-bajgain commented on index.html
>      <ul class="first_project_skill_list flex">
- [ ] I would suggest you please stick to the design as much as possible. your logo and content should be inline on the same line and also increase the width of the `p` tag so it matches the design. See the image below for reference. The text is aligned to the left but it doesn't pass the middle of the page.
### Your design
![his](https://user-images.githubusercontent.com/81727988/206657205-0974fb90-fb57-40b0-a528-20b18dd611a1.png)

### Figma design
![fimga](https://user-images.githubusercontent.com/81727988/206657242-10e1755b-abb6-4a3e-b281-4ef70ea1fc8c.png)

2022-12-09 08:50 UTC, roshan-bajgain commented on index.html
> +        <li class="nav_link_email"><a href="#"><img src="image folder/Disabled.png" alt=""></a></li>
- [ ] I would suggest you please stick to the design as much as possible. your logo and content should be inline on the same line and also increase the width of the `p` tag so it matches the design. See the image below for reference. The text is aligned to the left but it doesn't pass the middle of the page.
### Your design
![his](https://user-images.githubusercontent.com/81727988/206657205-0974fb90-fb57-40b0-a528-20b18dd611a1.png)

### Figma design
![fimga](https://user-images.githubusercontent.com/81727988/206657242-10e1755b-abb6-4a3e-b281-4ef70ea1fc8c.png)

2022-12-09 08:50 UTC, roshan-bajgain commented on index.html
> +    <div class="first_project">
- [ ]  i would suggest you please stick to the design as much as possible. The featured project image takes 60% of the page's width and is aligned to the left, the description takes the remaining 40% and is aligned to the right. There is equal padding from left and right. Please see the image below for reference.
- [ ] Kindly increase the font size of the placeholder of the `see-project` buttons.
### Your design
![his](https://user-images.githubusercontent.com/81727988/206658675-582144cb-39a5-4cb1-922c-a420c7d664ff.png)
### Figma design

![figma](https://user-images.githubusercontent.com/81727988/206658707-fb759443-2d93-4b53-adb0-c67da88445ec.png)

2022-12-09 08:50 UTC, roshan-bajgain commented on index.html
>      <ul class="third_project_skill_list flex">
- [ ] I would suggest please adjust the spacing on the left and right of the page. Also, stick to the design as much as possible. please fix the background and color of the button.
- [ ] please implement in all the cards
### Your design
![yourrrrr](https://user-images.githubusercontent.com/81727988/206659893-69260cb9-28c8-4a28-87ac-f99c40d00739.png)

### Figma design
![fogma](https://user-images.githubusercontent.com/81727988/206659915-a7162dcf-9fdd-4347-bc1f-1935f28252aa.png)

2022-12-09 22:01 UTC, Debas-31 requested changes
> ## Hi @3nityGitHub :wave:, 
# Status: Require Change :recycle:
Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media4.giphy.com/media/WTdg5GBR45X6NbxqJK/giphy.gif"/>


 ## Highlights
- No linters error  :heavy_check_mark:
- PR title and summary :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-10 00:05 UTC, abdulhamiid approved these changes
# :green_circle:  Approved! :partying_face:
Hi @3nityGitHub , 
![image](https://user-images.githubusercontent.com/55596970/158098566-50966056-ce3d-4c4b-aac3-cce7a7d107fb.png)
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 🌟

- ✔️ Descriptions are very descriptive
- ✔️ Linters checks are passing
- ✔️ Use GitHub Flow
- ✔️ Meaningful commit messages.

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-10 15:01 UTC, merged